"""
bracket_data.py — 2026 World Cup bracket structure and FIFA Annex C table.

The 2026 FIFA World Cup uses a 48-team format with a new Round of 32 and a
predefined 495-scenario lookup table (Annex C of the FIFA 2026 Competition
Regulations) that determines exactly which advancing third-placed team plays
which Round-of-32 group winner.

Sources:
  - FIFA 2026 Competition Regulations, Annex C
  - Wikipedia: "2026 FIFA World Cup knockout stage"
"""


# ---- Round of 32 schedule ----
# Each entry: (match_id, slot_a, slot_b)
# Slot "3?" means a third-placed team whose source group is determined by
# the 495-scenario Annex C lookup.

R32_SCHEDULE = [
    (73, "2A", "2B"),
    (74, "1E", "3?"),
    (75, "1F", "2C"),
    (76, "1C", "2F"),
    (77, "1I", "3?"),
    (78, "2E", "2I"),
    (79, "1A", "3?"),
    (80, "1L", "3?"),
    (81, "1D", "3?"),
    (82, "1G", "3?"),
    (83, "2K", "2L"),
    (84, "1H", "2J"),
    (85, "1B", "3?"),
    (86, "1J", "2H"),
    (87, "1K", "3?"),
    (88, "2D", "2G"),
]

# Slots that take third-placed teams, in Annex C column order.
# The 495-table's 8 source values map to these slots in this exact order.
THIRD_PLACE_SLOTS = ["1A", "1B", "1D", "1E", "1G", "1I", "1K", "1L"]

# For each third-place slot, the allowed source groups (FIFA constraint:
# no team plays an opponent from its own group in R32).
SLOT_ALLOWED_SETS = {
    "1A": set("CEFHI"),
    "1B": set("EFGIJ"),
    "1D": set("BEFIJ"),
    "1E": set("ABCDF"),
    "1G": set("AEHIJ"),
    "1I": set("CDFGH"),
    "1K": set("DEIJL"),
    "1L": set("EHIJK"),
}

# Knockout pairings beyond R32. (match_id, feeder_a_match_id, feeder_b_match_id)
BRACKET_PAIRINGS = {
    "R16": [
        (89, 74, 77),
        (90, 73, 75),
        (91, 76, 78),
        (92, 79, 80),
        (93, 83, 84),
        (94, 81, 82),
        (95, 86, 88),
        (96, 85, 87),
    ],
    "QF": [
        (97, 89, 90),
        (98, 93, 94),
        (99, 91, 92),
        (100, 95, 96),
    ],
    "SF": [
        (101, 97, 98),
        (102, 99, 100),
    ],
    "F": [
        (104, 101, 102),  # Match 103 is the 3rd-place playoff; we skip it.
    ],
}


# ---- Annex C: 495-scenario lookup table ----
# Each line: "KEY SOURCES" where KEY is the 8 sorted group letters of the
# advancing thirds, and SOURCES is the 8-letter source-group sequence in
# slot order (1A, 1B, 1D, 1E, 1G, 1I, 1K, 1L).

_ANNEX_C = """\
ABCDEFGH HGBCAFDE
ABCDEFGI CGBDAFEI
ABCDEFGJ CGBDAFEJ
ABCDEFGK CGBDAFEK
ABCDEFGL CGBDAFLE
ABCDEFHI HEBCAFDI
ABCDEFHJ HJBCAFDE
ABCDEFHK HEBCAFDK
ABCDEFHL HFBCADLE
ABCDEFIJ CJBDAFEI
ABCDEFIK CEBDAFIK
ABCDEFIL CEBDAFLI
ABCDEFJK CJBDAFEK
ABCDEFJL CJBDAFLE
ABCDEFKL CEBDAFLK
ABCDEGHI HGBCADEI
ABCDEGHJ HGBCADEJ
ABCDEGHK HGBCADEK
ABCDEGHL HGBCADLE
ABCDEGIJ EGBCADIJ
ABCDEGIK EGBCADIK
ABCDEGIL EGBCADLI
ABCDEGJK EGBCADJK
ABCDEGJL EGBCADLJ
ABCDEGKL EGBCADLK
ABCDEHIJ HJBCADEI
ABCDEHIK HEBCADIK
ABCDEHIL HEBCADLI
ABCDEHJK HJBCADEK
ABCDEHJL HJBCADLE
ABCDEHKL HEBCADLK
ABCDEIJK EJBCADIK
ABCDEIJL EJBCADLI
ABCDEIKL EIBCADLK
ABCDEJKL EJBCADLK
ABCDFGHI HGBCAFDI
ABCDFGHJ HGBCAFDJ
ABCDFGHK HGBCAFDK
ABCDFGHL CGBDAFLH
ABCDFGIJ CGBDAFIJ
ABCDFGIK CGBDAFIK
ABCDFGIL CGBDAFLI
ABCDFGJK CGBDAFJK
ABCDFGJL CGBDAFLJ
ABCDFGKL CGBDAFLK
ABCDFHIJ HJBCAFDI
ABCDFHIK HFBCADIK
ABCDFHIL HFBCADLI
ABCDFHJK HJBCAFDK
ABCDFHJL CJBDAFLH
ABCDFHKL HFBCADLK
ABCDFIJK CJBDAFIK
ABCDFIJL CJBDAFLI
ABCDFIKL CIBDAFLK
ABCDFJKL CJBDAFLK
ABCDGHIJ HGBCADIJ
ABCDGHIK HGBCADIK
ABCDGHIL HGBCADLI
ABCDGHJK HGBCADJK
ABCDGHJL HGBCADLJ
ABCDGHKL HGBCADLK
ABCDGIJK CJBDAGIK
ABCDGIJL CJBDAGLI
ABCDGIKL IGBCADLK
ABCDGJKL CJBDAGLK
ABCDHIJK HJBCADIK
ABCDHIJL HJBCADLI
ABCDHIKL HIBCADLK
ABCDHJKL HJBCADLK
ABCDIJKL IJBCADLK
ABCEFGHI HGBCAFEI
ABCEFGHJ HGBCAFEJ
ABCEFGHK HGBCAFEK
ABCEFGHL HGBCAFLE
ABCEFGIJ EGBCAFIJ
ABCEFGIK EGBCAFIK
ABCEFGIL EGBCAFLI
ABCEFGJK EGBCAFJK
ABCEFGJL EGBCAFLJ
ABCEFGKL EGBCAFLK
ABCEFHIJ HJBCAFEI
ABCEFHIK HEBCAFIK
ABCEFHIL HEBCAFLI
ABCEFHJK HJBCAFEK
ABCEFHJL HJBCAFLE
ABCEFHKL HEBCAFLK
ABCEFIJK EJBCAFIK
ABCEFIJL EJBCAFLI
ABCEFIKL EIBCAFLK
ABCEFJKL EJBCAFLK
ABCEGHIJ HJBCAGEI
ABCEGHIK EGBCAHIK
ABCEGHIL EGBCAHLI
ABCEGHJK HJBCAGEK
ABCEGHJL HJBCAGLE
ABCEGHKL EGBCAHLK
ABCEGIJK EJBCAGIK
ABCEGIJL EJBCAGLI
ABCEGIKL EGBAICLK
ABCEGJKL EJBCAGLK
ABCEHIJK EJBCAHIK
ABCEHIJL EJBCAHLI
ABCEHIKL EIBCAHLK
ABCEHJKL EJBCAHLK
ABCEIJKL EJBAICLK
ABCFGHIJ HGBCAFIJ
ABCFGHIK HGBCAFIK
ABCFGHIL HGBCAFLI
ABCFGHJK HGBCAFJK
ABCFGHJL HGBCAFLJ
ABCFGHKL HGBCAFLK
ABCFGIJK CJBFAGIK
ABCFGIJL CJBFAGLI
ABCFGIKL IGBCAFLK
ABCFGJKL CJBFAGLK
ABCFHIJK HJBCAFIK
ABCFHIJL HJBCAFLI
ABCFHIKL HIBCAFLK
ABCFHJKL HJBCAFLK
ABCFIJKL IJBCAFLK
ABCGHIJK HJBCAGIK
ABCGHIJL HJBCAGLI
ABCGHIKL IGBCAHLK
ABCGHJKL HJBCAGLK
ABCGIJKL IJBCAGLK
ABCHIJKL IJBCAHLK
ABDEFGHI HGBDAFEI
ABDEFGHJ HGBDAFEJ
ABDEFGHK HGBDAFEK
ABDEFGHL HGBDAFLE
ABDEFGIJ EGBDAFIJ
ABDEFGIK EGBDAFIK
ABDEFGIL EGBDAFLI
ABDEFGJK EGBDAFJK
ABDEFGJL EGBDAFLJ
ABDEFGKL EGBDAFLK
ABDEFHIJ HJBDAFEI
ABDEFHIK HEBDAFIK
ABDEFHIL HEBDAFLI
ABDEFHJK HJBDAFEK
ABDEFHJL HJBDAFLE
ABDEFHKL HEBDAFLK
ABDEFIJK EJBDAFIK
ABDEFIJL EJBDAFLI
ABDEFIKL EIBDAFLK
ABDEFJKL EJBDAFLK
ABDEGHIJ HJBDAGEI
ABDEGHIK EGBDAHIK
ABDEGHIL EGBDAHLI
ABDEGHJK HJBDAGEK
ABDEGHJL HJBDAGLE
ABDEGHKL EGBDAHLK
ABDEGIJK EJBDAGIK
ABDEGIJL EJBDAGLI
ABDEGIKL EGBAIDLK
ABDEGJKL EJBDAGLK
ABDEHIJK EJBDAHIK
ABDEHIJL EJBDAHLI
ABDEHIKL EIBDAHLK
ABDEHJKL EJBDAHLK
ABDEIJKL EJBAIDLK
ABDFGHIJ HGBDAFIJ
ABDFGHIK HGBDAFIK
ABDFGHIL HGBDAFLI
ABDFGHJK HGBDAFJK
ABDFGHJL HGBDAFLJ
ABDFGHKL HGBDAFLK
ABDFGIJK FJBDAGIK
ABDFGIJL FJBDAGLI
ABDFGIKL IGBDAFLK
ABDFGJKL FJBDAGLK
ABDFHIJK HJBDAFIK
ABDFHIJL HJBDAFLI
ABDFHIKL HIBDAFLK
ABDFHJKL HJBDAFLK
ABDFIJKL IJBDAFLK
ABDGHIJK HJBDAGIK
ABDGHIJL HJBDAGLI
ABDGHIKL IGBDAHLK
ABDGHJKL HJBDAGLK
ABDGIJKL IJBDAGLK
ABDHIJKL IJBDAHLK
ABEFGHIJ HJBFAGEI
ABEFGHIK EGBFAHIK
ABEFGHIL EGBFAHLI
ABEFGHJK HJBFAGEK
ABEFGHJL HJBFAGLE
ABEFGHKL EGBFAHLK
ABEFGIJK EJBFAGIK
ABEFGIJL EJBFAGLI
ABEFGIKL EGBAIFLK
ABEFGJKL EJBFAGLK
ABEFHIJK EJBFAHIK
ABEFHIJL EJBFAHLI
ABEFHIKL EIBFAHLK
ABEFHJKL EJBFAHLK
ABEFIJKL EJBAIFLK
ABEGHIJK EJBAHGIK
ABEGHIJL EJBAHGLI
ABEGHIKL EGBAIHLK
ABEGHJKL EJBAHGLK
ABEGIJKL EJBAIGLK
ABEHIJKL EJBAIHLK
ABFGHIJK HJBFAGIK
ABFGHIJL HJBFAGLI
ABFGHIKL HGBAIFLK
ABFGHJKL HJBFAGLK
ABFGIJKL IJBFAGLK
ABFHIJKL HJBAIFLK
ABGHIJKL HJBAIGLK
ACDEFGHI HGECAFDI
ACDEFGHJ HGJCAFDE
ACDEFGHK HGECAFDK
ACDEFGHL HGFCADLE
ACDEFGIJ CGJDAFEI
ACDEFGIK CGEDAFIK
ACDEFGIL CGEDAFLI
ACDEFGJK CGJDAFEK
ACDEFGJL CGJDAFLE
ACDEFGKL CGEDAFLK
ACDEFHIJ HJECAFDI
ACDEFHIK HEFCADIK
ACDEFHIL HEFCADLI
ACDEFHJK HJECAFDK
ACDEFHJL HJFCADLE
ACDEFHKL HEFCADLK
ACDEFIJK CJEDAFIK
ACDEFIJL CJEDAFLI
ACDEFIKL CEIDAFLK
ACDEFJKL CJEDAFLK
ACDEGHIJ HGJCADEI
ACDEGHIK HGECADIK
ACDEGHIL HGECADLI
ACDEGHJK HGJCADEK
ACDEGHJL HGJCADLE
ACDEGHKL HGECADLK
ACDEGIJK EGJCADIK
ACDEGIJL EGJCADLI
ACDEGIKL EGICADLK
ACDEGJKL EGJCADLK
ACDEHIJK HJECADIK
ACDEHIJL HJECADLI
ACDEHIKL HEICADLK
ACDEHJKL HJECADLK
ACDEIJKL EJICADLK
ACDFGHIJ HGJCAFDI
ACDFGHIK HGFCADIK
ACDFGHIL HGFCADLI
ACDFGHJK HGJCAFDK
ACDFGHJL CGJDAFLH
ACDFGHKL HGFCADLK
ACDFGIJK CGJDAFIK
ACDFGIJL CGJDAFLI
ACDFGIKL CGIDAFLK
ACDFGJKL CGJDAFLK
ACDFHIJK HJFCADIK
ACDFHIJL HJFCADLI
ACDFHIKL HFICADLK
ACDFHJKL HJFCADLK
ACDFIJKL CJIDAFLK
ACDGHIJK HGJCADIK
ACDGHIJL HGJCADLI
ACDGHIKL HGICADLK
ACDGHJKL HGJCADLK
ACDGIJKL IGJCADLK
ACDHIJKL HJICADLK
ACEFGHIJ HGJCAFEI
ACEFGHIK HGECAFIK
ACEFGHIL HGECAFLI
ACEFGHJK HGJCAFEK
ACEFGHJL HGJCAFLE
ACEFGHKL HGECAFLK
ACEFGIJK EGJCAFIK
ACEFGIJL EGJCAFLI
ACEFGIKL EGICAFLK
ACEFGJKL EGJCAFLK
ACEFHIJK HJECAFIK
ACEFHIJL HJECAFLI
ACEFHIKL HEICAFLK
ACEFHJKL HJECAFLK
ACEFIJKL EJICAFLK
ACEGHIJK EGJCAHIK
ACEGHIJL EGJCAHLI
ACEGHIKL EGICAHLK
ACEGHJKL EGJCAHLK
ACEGIJKL EJICAGLK
ACEHIJKL EJICAHLK
ACFGHIJK HGJCAFIK
ACFGHIJL HGJCAFLI
ACFGHIKL HGICAFLK
ACFGHJKL HGJCAFLK
ACFGIJKL IGJCAFLK
ACFHIJKL HJICAFLK
ACGHIJKL HJICAGLK
ADEFGHIJ HGJDAFEI
ADEFGHIK HGEDAFIK
ADEFGHIL HGEDAFLI
ADEFGHJK HGJDAFEK
ADEFGHJL HGJDAFLE
ADEFGHKL HGEDAFLK
ADEFGIJK EGJDAFIK
ADEFGIJL EGJDAFLI
ADEFGIKL EGIDAFLK
ADEFGJKL EGJDAFLK
ADEFHIJK HJEDAFIK
ADEFHIJL HJEDAFLI
ADEFHIKL HEIDAFLK
ADEFHJKL HJEDAFLK
ADEFIJKL EJIDAFLK
ADEGHIJK EGJDAHIK
ADEGHIJL EGJDAHLI
ADEGHIKL EGIDAHLK
ADEGHJKL EGJDAHLK
ADEGIJKL EJIDAGLK
ADEHIJKL EJIDAHLK
ADFGHIJK HGJDAFIK
ADFGHIJL HGJDAFLI
ADFGHIKL HGIDAFLK
ADFGHJKL HGJDAFLK
ADFGIJKL IGJDAFLK
ADFHIJKL HJIDAFLK
ADGHIJKL HJIDAGLK
AEFGHIJK EGJFAHIK
AEFGHIJL EGJFAHLI
AEFGHIKL EGIFAHLK
AEFGHJKL EGJFAHLK
AEFGIJKL EJIFAGLK
AEFHIJKL EJIFAHLK
AEGHIJKL EJIAHGLK
AFGHIJKL HJIFAGLK
BCDEFGHI CGBDHFEI
BCDEFGHJ HGBCJFDE
BCDEFGHK CGBDHFEK
BCDEFGHL CGBDHFLE
BCDEFGIJ CGBDJFEI
BCDEFGIK CGBDEFIK
BCDEFGIL CGBDEFLI
BCDEFGJK CGBDJFEK
BCDEFGJL CGBDJFLE
BCDEFGKL CGBDEFLK
BCDEFHIJ CJBDHFEI
BCDEFHIK CEBDHFIK
BCDEFHIL CEBDHFLI
BCDEFHJK CJBDHFEK
BCDEFHJL CJBDHFLE
BCDEFHKL CEBDHFLK
BCDEFIJK CJBDEFIK
BCDEFIJL CJBDEFLI
BCDEFIKL CEBDIFLK
BCDEFJKL CJBDEFLK
BCDEGHIJ HGBCJDEI
BCDEGHIK EGBCHDIK
BCDEGHIL EGBCHDLI
BCDEGHJK HGBCJDEK
BCDEGHJL HGBCJDLE
BCDEGHKL EGBCHDLK
BCDEGIJK EGBCJDIK
BCDEGIJL EGBCJDLI
BCDEGIKL EGBCIDLK
BCDEGJKL EGBCJDLK
BCDEHIJK EJBCHDIK
BCDEHIJL EJBCHDLI
BCDEHIKL EIBCHDLK
BCDEHJKL EJBCHDLK
BCDEIJKL EJBCIDLK
BCDFGHIJ HGBCJFDI
BCDFGHIK CGBDHFIK
BCDFGHIL CGBDHFLI
BCDFGHJK HGBCJFDK
BCDFGHJL CGBDHFLJ
BCDFGHKL CGBDHFLK
BCDFGIJK CGBDJFIK
BCDFGIJL CGBDJFLI
BCDFGIKL CGBDIFLK
BCDFGJKL CGBDJFLK
BCDFHIJK CJBDHFIK
BCDFHIJL CJBDHFLI
BCDFHIKL CIBDHFLK
BCDFHJKL CJBDHFLK
BCDFIJKL CJBDIFLK
BCDGHIJK HGBCJDIK
BCDGHIJL HGBCJDLI
BCDGHIKL HGBCIDLK
BCDGHJKL HGBCJDLK
BCDGIJKL IGBCJDLK
BCDHIJKL HJBCIDLK
BCEFGHIJ HGBCJFEI
BCEFGHIK EGBCHFIK
BCEFGHIL EGBCHFLI
BCEFGHJK HGBCJFEK
BCEFGHJL HGBCJFLE
BCEFGHKL EGBCHFLK
BCEFGIJK EGBCJFIK
BCEFGIJL EGBCJFLI
BCEFGIKL EGBCIFLK
BCEFGJKL EGBCJFLK
BCEFHIJK EJBCHFIK
BCEFHIJL EJBCHFLI
BCEFHIKL EIBCHFLK
BCEFHJKL EJBCHFLK
BCEFIJKL EJBCIFLK
BCEGHIJK EJBCHGIK
BCEGHIJL EJBCHGLI
BCEGHIKL EGBCIHLK
BCEGHJKL EJBCHGLK
BCEGIJKL EJBCIGLK
BCEHIJKL EJBCIHLK
BCFGHIJK HGBCJFIK
BCFGHIJL HGBCJFLI
BCFGHIKL HGBCIFLK
BCFGHJKL HGBCJFLK
BCFGIJKL IGBCJFLK
BCFHIJKL HJBCIFLK
BCGHIJKL HJBCIGLK
BDEFGHIJ HGBDJFEI
BDEFGHIK EGBDHFIK
BDEFGHIL EGBDHFLI
BDEFGHJK HGBDJFEK
BDEFGHJL HGBDJFLE
BDEFGHKL EGBDHFLK
BDEFGIJK EGBDJFIK
BDEFGIJL EGBDJFLI
BDEFGIKL EGBDIFLK
BDEFGJKL EGBDJFLK
BDEFHIJK EJBDHFIK
BDEFHIJL EJBDHFLI
BDEFHIKL EIBDHFLK
BDEFHJKL EJBDHFLK
BDEFIJKL EJBDIFLK
BDEGHIJK EJBDHGIK
BDEGHIJL EJBDHGLI
BDEGHIKL EGBDIHLK
BDEGHJKL EJBDHGLK
BDEGIJKL EJBDIGLK
BDEHIJKL EJBDIHLK
BDFGHIJK HGBDJFIK
BDFGHIJL HGBDJFLI
BDFGHIKL HGBDIFLK
BDFGHJKL HGBDJFLK
BDFGIJKL IGBDJFLK
BDFHIJKL HJBDIFLK
BDGHIJKL HJBDIGLK
BEFGHIJK EJBFHGIK
BEFGHIJL EJBFHGLI
BEFGHIKL EGBFIHLK
BEFGHJKL EJBFHGLK
BEFGIJKL EJBFIGLK
BEFHIJKL EJBFIHLK
BEGHIJKL EJIBHGLK
BFGHIJKL HJBFIGLK
CDEFGHIJ CGJDHFEI
CDEFGHIK CGEDHFIK
CDEFGHIL CGEDHFLI
CDEFGHJK CGJDHFEK
CDEFGHJL CGJDHFLE
CDEFGHKL CGEDHFLK
CDEFGIJK CGEDJFIK
CDEFGIJL CGEDJFLI
CDEFGIKL CGEDIFLK
CDEFGJKL CGEDJFLK
CDEFHIJK CJEDHFIK
CDEFHIJL CJEDHFLI
CDEFHIKL CEIDHFLK
CDEFHJKL CJEDHFLK
CDEFIJKL CJEDIFLK
CDEGHIJK EGJCHDIK
CDEGHIJL EGJCHDLI
CDEGHIKL EGICHDLK
CDEGHJKL EGJCHDLK
CDEGIJKL EGICJDLK
CDEHIJKL EJICHDLK
CDFGHIJK CGJDHFIK
CDFGHIJL CGJDHFLI
CDFGHIKL CGIDHFLK
CDFGHJKL CGJDHFLK
CDFGIJKL CGIDJFLK
CDFHIJKL CJIDHFLK
CDGHIJKL HGICJDLK
CEFGHIJK EGJCHFIK
CEFGHIJL EGJCHFLI
CEFGHIKL EGICHFLK
CEFGHJKL EGJCHFLK
CEFGIJKL EGICJFLK
CEFHIJKL EJICHFLK
CEGHIJKL EJICHGLK
CFGHIJKL HGICJFLK
DEFGHIJK EGJDHFIK
DEFGHIJL EGJDHFLI
DEFGHIKL EGIDHFLK
DEFGHJKL EGJDHFLK
DEFGIJKL EGIDJFLK
DEFHIJKL EJIDHFLK
DEGHIJKL EJIDHGLK
DFGHIJKL HGIDJFLK
EFGHIJKL EJIFHGLK
"""


def _parse_annex_c(raw: str) -> dict:
    table = {}
    for line in raw.strip().split("\n"):
        line = line.strip()
        if not line:
            continue
        key, sources = line.split()
        if len(key) != 8 or len(sources) != 8:
            raise ValueError(f"Bad Annex C line: {line!r}")
        table[key] = tuple(sources)
    return table


THIRD_PLACE_TABLE = _parse_annex_c(_ANNEX_C)
assert len(THIRD_PLACE_TABLE) == 495, (
    f"Expected 495 Annex C scenarios, parsed {len(THIRD_PLACE_TABLE)}"
)


def get_third_place_assignment(qualifying_groups) -> dict:
    """Look up the FIFA Annex C slot assignment for a set of 8 qualifying groups.

    Args:
        qualifying_groups: iterable of 8 group letters (e.g. ["A", "B", "C", ...])

    Returns:
        dict mapping each third-place slot label ("1A", "1B", ...) to the
        source group letter whose third-placed team plays in that slot.
    """
    groups = list(qualifying_groups)
    if len(groups) != 8:
        raise ValueError(f"Need exactly 8 groups, got {len(groups)}: {groups}")
    key = "".join(sorted(groups))
    if key not in THIRD_PLACE_TABLE:
        raise KeyError(f"No Annex C entry for {sorted(groups)}")
    sources = THIRD_PLACE_TABLE[key]
    return dict(zip(THIRD_PLACE_SLOTS, sources))
